name: 'Create a GitHub Issue'
description: 'Creates a GitHub issue.'
inputs:
  token:
    description: 'The GitHub access token.'
    required: true
  issue_number:
    description: 'The number of the issue.'
    required: true
  label:
    description: 'The label to associate with this issue.'
    required: true
outputs:
  issue:
    description: 'The updated issue.'
runs:
  using: 'node12'
  main: 'index.js'