name: 'Create GitHub Issue'
description: 'Creates a GitHub issue'
inputs:
  action-id:
    description: 'GitHub Action ID'
    required: true
    default: ''
  title:
    description: 'Title of the issue'
    required: true
    default: 'Release Created'
  package-version:
    description: 'Version of the package being released'
    required: true
    default: 'Something like 1.0.0'
outputs:
  issue-id:
    description: 'ID of the created issue on GitHub'
runs:
  using: 'node12'
  main: 'dist/index.js'