name: 'Create a GitHub Issue'
description: 'Creates a GitHub issue.'
inputs:
  token:
    description: 'The GitHub access token.'
    required: true
  title:
    description: 'The title of the issue.'
    required: true
  labels:
    description: 'Labels to associate with this issue.'
    required: false
  assignee:
    description: 'Login for the user that this issue should be assigned to.'
    required: false
  body:
    description: 'The contents of the issue.'
    required: false
runs:
  using: 'node12'
  main: 'index.js'