name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - uses: Azure/login@v1
      with:
        creds: ${{ secrets.DEVELOP_AZURECREDENTIALS }} 
    - uses: Azure/get-keyvault-secrets@v1.0
      with:
        keyvault: "mjr-066-001-kv"
        secrets: 'CosmosConnectionString1,FunctionApp1Code,StorageConnectionString1' 
      id: GetSecrets
