name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    # - uses: actions/checkout@v2
    # - name: Setup .NET Core
    #   uses: actions/setup-dotnet@v1
    #   with:
    #     dotnet-version: 3.1.301
    # - name: Install dependencies
    #   run: dotnet restore
    # - name: Build
    #   run: dotnet build --configuration Release --no-restore
    # - name: Test
    #   run: dotnet test --no-restore --verbosity normal

    - uses: actions/checkout@master
    - uses: Azure/login@v1
      with:
        creds: ${{ secrets.DEVELOP_AZURECREDENTIALS }} 
    - uses: Azure/get-keyvault-secrets@v1.0
      with:
        keyvault: "mjr-066-001-kv"
        secrets: 'CosmosConnectionString1,FunctionApp1Code,StorageConnectionString1' 
      id: GetSecrets

    - name: Run Azure PowerShell script
      uses: azure/powershell@v1
      with:
        inlineScript: |
          $ResourceGroupName = "mjr-066-001-rg"
          $ResourceGroup = (Get-AzResourceGroup -Name $ResourceGroupName -ErrorAction SilentlyContinue)

          if ($null -eq $ResourceGroup) {
              $ResourceGroup = (New-AzResourceGroup `
                  -Name $ResourceGroupName `
                  -Location $ResourceGroupLocation)
          }
        azPSVersion: '3.1.0'
