name: Staging

on:
  issues:
    types: [labeled]

jobs:
        
  deploy-infrastructure:
    
    runs-on: ubuntu-latest

    steps: 
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "12.x"
      - uses: ./.github/actions/check-issue
        id: CheckIssue
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          label: approved