name: Staging

on:
  issues:
    types: [labeled]

jobs:
        
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/hello-world
        id: hello
        with:
          who-to-greet: 'Mona the Octocat'
      - run: echo "The time was ${{ steps.hello.outputs.time }}"