name: Staging

on:
  label:
    types: [created]

jobs:
        
  deploy-infrastructure:
    
    runs-on: ubuntu-latest

    steps: 
      - name: Check issue was release issue
        uses: ./.github/actions/check-issue
        id: check-issue
        with:
            token: ${{ secrets.GITHUB_TOKEN }}
            label: approved