name: Staging

on:
  issues:
    types: [labeled]

jobs:
        
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "12.x"
      - run: npm install
        working-directory: ./.github/actions/hello-world
      - uses: ./.github/actions/hello-world
        id: hello
        with:
          who-to-greet: 'Mona the Octocat'
      - run: echo "The time was ${{ steps.hello.outputs.time }}"