name: Staging

on:
  issues:
    types: [labeled]

jobs:
        
  deploy-infrastructure:
    
    runs-on: ubuntu-latest

    steps: 
      - uses: actions/checkout@v2
      - name: Check issue was release issue
        uses: ./.github/actions/check-issue
        id: CheckIssue
        with:
            token: ${{ secrets.GITHUB_TOKEN }}
            label: approved