name: Staging

env:
  OUTPUT_PATH: ${{ github.workspace }}/.output

on:
  issues:
    types: [labeled]

jobs:
        
  deploy-infrastructure:
    
    runs-on: ubuntu-latest

    steps: 
      - uses: actions/checkout@v2
      - name: Prepare create release issue action
        uses: actions/setup-node@v1
        with:
          node-version: "12.x"
      - name: Building Action
        run: npm i && npm run build
        working-directory: ./.github/actions/check-issue
      - name: Check issue was release issue
        uses: ./.github/actions/check-issue
        id: CheckIssue
        with:
            token: ${{ secrets.GITHUB_TOKEN }}
            label: approved